# overlays/dev/kustomization.yaml — dev overlay (smallest patch over W5 D3 base).
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: multistate-dev

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"

images:
- name: uptimecrew/multistate-api
  newName: uptimecrew/multistate-api
  newTag: dba8f4fcc9ec75a45b0805f6b49928b2f93f7bdd

replicas:
- count: 1
  name: multistate-api

patches:
- patch: |-
    - op: replace
      path: /data/SPRING_PROFILES_ACTIVE
      value: k8s
    - op: replace
      path: /data/LOGGING_LEVEL_ROOT
      value: DEBUG
  target:
    kind: ConfigMap
    name: multistate-api-config
