# multistate-agent-svc/base/50-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: multistate-agent-svc
  namespace: multistate-svc
  labels:
    app.kubernetes.io/name: multistate-agent-svc
    app.kubernetes.io/part-of: multistate
